#define BLUETOOTH_DISCOVERY_TIMEOUT_SECONDS 1

#define BLUETOOTH_SERVICE_NAME "JSC Nerf Turret"
#define BLUETOOTH_SERVICE_DESCRIPTION "Service for the JSC Nerf Turret"
#define BLUETOOTH_SERVICE_PROVIDER "JScoobyCed"
#define BLUETOOTH_SERVICE_CHANNEL 22

#define BLUETOOTH_SERVICE_PATH "/org/bluez/jscturret"
#define BLUETOOTH_SERVICE_UUID "AD423591-A6EC-495A-996B-5B56B5704E52"