#define BLUETOOTH_BASE_128_UUID "00000000-0000-1000-8000-00805F9B34FB"
#define SERIAL_PORT_PROFILE_UUID "00001101-0000-1000-8000-00805f9b34fb"

#define BLUEZ "org.bluez"
#define BLUETOOTH_PATH_BASE "/org/bluez"
#define BLUETOOTH_PATH_DEFAULT "/org/bluez/hci0"
#define BLUETOOTH_DEVICE_DEFAULT "org.bluez.Device1"
#define BLUETOOTH_ADAPTER_DEFAULT "org.bluez.Adapter1"
#define BLUETOOTH_PROFILE_DEFAULT "org.bluez.Profile1"
#define BLUETOOTH_PROFILE_MANAGER_DEFAULT "org.bluez.ProfileManager1"

#define BLUETOOTH_NAME_MAX_LENGTH_BYTES 248
#define BLUETOOTH_ADDRESS_STRING_SIZE 18
#define BLUETOOTH_ADAPTER_STRING_SIZE 32
#define BLUETOOTH_UUID_STRING_SIZE 64
#define BLUETOOTH_DISCOVERY_MAX_WAIT_SECONDS 10

#define ERR_CANNOT_GET_DBUS_CONNECTION 500
#define ERR_CANNOT_ENABLE_ADAPTER 501
#define ERR_CANNOT_DISABLE_ADAPTER 502
#define ERR_CANNOT_START_SCAN 503
#define ERR_CANNOT_STOP_SCAN 504
#define ERR_CUSTOM_PATH_INVALID 505
#define ERR_CANNOT_REGISTER_PROFILE 506
#define ERR_CANNOT_REGISTER_NEW_CONNECTION 507
#define ERR_CANNOT_CONNECT_DEVICE 508
#define ERR_CANNOT_CALL_METHOD 509

#define RESULT_OK 200
